Description: ALB And ECS
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-003e6ce74c0ec695d, sg-039879afee519f8a8
  SubnetIds:
    Type: CommaDelimitedList
    Default: subnet-01405f62e49e3721d, subnet-03a2d434cd2925e93, subnet-095ddd203f02bcfa2, subnet-0cc9d8c14b31e5042, subnet-0f9184e762d15e064, subnet-0a11cbaf3d16480a1
  VpcId:
    Type: String
    Default: vpc-0836c2a075ecb38cc
  PrefixedServiceName:
    Type: String
  DnsPrefix:
    Type: String
  CostCenterTag:
    Type: String

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${PrefixedServiceName}-lb"
      SecurityGroups: !Ref SecurityGroupIds
      Subnets: !Ref SubnetIds
      Tags:
        - Key: "CostCenter"
          Value: !Ref CostCenterTag

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${PrefixedServiceName}-tg"
      VpcId: !Ref VpcId
      Protocol: HTTPS
      Port: 8443
      TargetType: ip
      HealthCheckProtocol: HTTPS
      HealthCheckPort: 8443
      HealthCheckPath: /actuator/health
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "300"
      Tags:
        - Key: "CostCenter"
          Value: !Ref CostCenterTag
